package com.ecommerce.dao;

import com.ecommerce.dataobject.OrderDO;
import com.mysql.cj.x.protobuf.MysqlxCrud;

import java.util.List;

public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    int deleteByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    int insertSelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    OrderDO selectByPrimaryKey(String orderid);

     List<OrderDO> selectOrdersByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    int updateByPrimaryKey(OrderDO record);
}