package com.ecommerce.dao;

import com.ecommerce.dataobject.ProductStockDO;
import com.ecommerce.dataobject.PromoDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ProductStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    int insert(ProductStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    int insertSelective(ProductStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    ProductStockDO selectByPrimaryKey(Integer id);

    ProductStockDO selectByProductId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    int updateByPrimaryKeySelective(ProductStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    int updateByPrimaryKey(ProductStockDO record);

    int decreaseStock(@Param("productId") Integer productId ,@Param("orderAmount") Integer orderAmount);

}