package com.ecommerce.dao;

import com.ecommerce.dataobject.ProductDO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ProductDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    int insert(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    int insertSelective(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    ProductDO selectByPrimaryKey(Integer id);

    List<ProductDO> selectProductList();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    int updateByPrimaryKeySelective(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    int updateByPrimaryKey(ProductDO record);
}