package com.ecommerce.dao;

import com.ecommerce.dataobject.PromoDO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PromoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    int insert(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    int insertSelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    PromoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    int updateByPrimaryKeySelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    int updateByPrimaryKey(PromoDO record);

    PromoDO selectByProductId(Integer productId);

    List<PromoDO> getAllPromoEvent();
}