package com.ecommerce.dao;

import com.ecommerce.dataobject.SequenceDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_sequence_info
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_sequence_info
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    int insert(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_sequence_info
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    int insertSelective(SequenceDO record);

    SequenceDO getSequenceByName(String name);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_sequence_info
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    SequenceDO selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_sequence_info
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    int updateByPrimaryKeySelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_sequence_info
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    int updateByPrimaryKey(SequenceDO record);
}