package com.ecommerce.dataobject;

public class OrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.orderId
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.userId
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.productId
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.orderAmount
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    private Integer orderamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.productPrice
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    private Double productprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.orderPrice
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    private Double orderprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.isFlashSale
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    private Byte isflashsale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.promoId
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    private Integer promoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.orderId
     *
     * @return the value of order_info.orderId
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.orderId
     *
     * @param orderid the value for order_info.orderId
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.userId
     *
     * @return the value of order_info.userId
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.userId
     *
     * @param userid the value for order_info.userId
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.productId
     *
     * @return the value of order_info.productId
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.productId
     *
     * @param productid the value for order_info.productId
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.orderAmount
     *
     * @return the value of order_info.orderAmount
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public Integer getOrderamount() {
        return orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.orderAmount
     *
     * @param orderamount the value for order_info.orderAmount
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public void setOrderamount(Integer orderamount) {
        this.orderamount = orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.productPrice
     *
     * @return the value of order_info.productPrice
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public Double getProductprice() {
        return productprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.productPrice
     *
     * @param productprice the value for order_info.productPrice
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public void setProductprice(Double productprice) {
        this.productprice = productprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.orderPrice
     *
     * @return the value of order_info.orderPrice
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public Double getOrderprice() {
        return orderprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.orderPrice
     *
     * @param orderprice the value for order_info.orderPrice
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public void setOrderprice(Double orderprice) {
        this.orderprice = orderprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.isFlashSale
     *
     * @return the value of order_info.isFlashSale
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public Byte getIsflashsale() {
        return isflashsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.isFlashSale
     *
     * @param isflashsale the value for order_info.isFlashSale
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public void setIsflashsale(Byte isflashsale) {
        this.isflashsale = isflashsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.promoId
     *
     * @return the value of order_info.promoId
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public Integer getPromoid() {
        return promoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.promoId
     *
     * @param promoid the value for order_info.promoId
     *
     * @mbg.generated Wed Jan 04 00:36:54 AEDT 2023
     */
    public void setPromoid(Integer promoid) {
        this.promoid = promoid;
    }
}