package com.ecommerce.dataobject;

public class ProductDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.title
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.price
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.description
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.sales
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.imgUrl
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private String imgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.id
     *
     * @return the value of product_info.id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.id
     *
     * @param id the value for product_info.id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.title
     *
     * @return the value of product_info.title
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.title
     *
     * @param title the value for product_info.title
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.price
     *
     * @return the value of product_info.price
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.price
     *
     * @param price the value for product_info.price
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.description
     *
     * @return the value of product_info.description
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.description
     *
     * @param description the value for product_info.description
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.sales
     *
     * @return the value of product_info.sales
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.sales
     *
     * @param sales the value for product_info.sales
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.imgUrl
     *
     * @return the value of product_info.imgUrl
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.imgUrl
     *
     * @param imgurl the value for product_info.imgUrl
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }
}