package com.ecommerce.dataobject;

import java.util.Date;

public class PromoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.id
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.promoName
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    private String promoname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.startDate
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.productId
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.promoPrice
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    private Double promoprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.endDate
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    private Date enddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.id
     *
     * @return the value of promo.id
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.id
     *
     * @param id the value for promo.id
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.promoName
     *
     * @return the value of promo.promoName
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    public String getPromoname() {
        return promoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.promoName
     *
     * @param promoname the value for promo.promoName
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    public void setPromoname(String promoname) {
        this.promoname = promoname == null ? null : promoname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.startDate
     *
     * @return the value of promo.startDate
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.startDate
     *
     * @param startdate the value for promo.startDate
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.productId
     *
     * @return the value of promo.productId
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.productId
     *
     * @param productid the value for promo.productId
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.promoPrice
     *
     * @return the value of promo.promoPrice
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    public Double getPromoprice() {
        return promoprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.promoPrice
     *
     * @param promoprice the value for promo.promoPrice
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    public void setPromoprice(Double promoprice) {
        this.promoprice = promoprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.endDate
     *
     * @return the value of promo.endDate
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.endDate
     *
     * @param enddate the value for promo.endDate
     *
     * @mbg.generated Tue Jan 03 20:27:13 AEDT 2023
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
}