package com.ecommerce.dataobject;

public class SequenceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_sequence_info.name
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_sequence_info.curr_value
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    private Integer currValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_sequence_info.step
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    private Integer step;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_sequence_info.name
     *
     * @return the value of order_sequence_info.name
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_sequence_info.name
     *
     * @param name the value for order_sequence_info.name
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_sequence_info.curr_value
     *
     * @return the value of order_sequence_info.curr_value
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    public Integer getCurrValue() {
        return currValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_sequence_info.curr_value
     *
     * @param currValue the value for order_sequence_info.curr_value
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    public void setCurrValue(Integer currValue) {
        this.currValue = currValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_sequence_info.step
     *
     * @return the value of order_sequence_info.step
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_sequence_info.step
     *
     * @param step the value for order_sequence_info.step
     *
     * @mbg.generated Tue Jan 03 12:09:19 AEDT 2023
     */
    public void setStep(Integer step) {
        this.step = step;
    }
}