package com.ecommerce.dataobject;

public class StockLogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.stock_log_id
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    private String stockLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.product_id
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.order_amount
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    private Integer orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.status
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.isFlashSale
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    private Byte isflashsale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.stock_log_id
     *
     * @return the value of stock_log.stock_log_id
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    public String getStockLogId() {
        return stockLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.stock_log_id
     *
     * @param stockLogId the value for stock_log.stock_log_id
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    public void setStockLogId(String stockLogId) {
        this.stockLogId = stockLogId == null ? null : stockLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.product_id
     *
     * @return the value of stock_log.product_id
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.product_id
     *
     * @param productId the value for stock_log.product_id
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.order_amount
     *
     * @return the value of stock_log.order_amount
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    public Integer getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.order_amount
     *
     * @param orderAmount the value for stock_log.order_amount
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    public void setOrderAmount(Integer orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.status
     *
     * @return the value of stock_log.status
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.status
     *
     * @param status the value for stock_log.status
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.isFlashSale
     *
     * @return the value of stock_log.isFlashSale
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    public Byte getIsflashsale() {
        return isflashsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.isFlashSale
     *
     * @param isflashsale the value for stock_log.isFlashSale
     *
     * @mbg.generated Wed Jan 11 21:54:58 AEDT 2023
     */
    public void setIsflashsale(Byte isflashsale) {
        this.isflashsale = isflashsale;
    }
}