package com.ecommerce.dataobject;

public class UserPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encrypt_password.id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encrypt_password.encrypy_password
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private String encrypyPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encrypt_password.user_id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encrypt_password.id
     *
     * @return the value of encrypt_password.id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encrypt_password.id
     *
     * @param id the value for encrypt_password.id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encrypt_password.encrypy_password
     *
     * @return the value of encrypt_password.encrypy_password
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public String getEncrypyPassword() {
        return encrypyPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encrypt_password.encrypy_password
     *
     * @param encrypyPassword the value for encrypt_password.encrypy_password
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setEncrypyPassword(String encrypyPassword) {
        this.encrypyPassword = encrypyPassword == null ? null : encrypyPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encrypt_password.user_id
     *
     * @return the value of encrypt_password.user_id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encrypt_password.user_id
     *
     * @param userId the value for encrypt_password.user_id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}