package com.ecommerce.dataobject;

public class UserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Name
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Gender
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Age
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Phone
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Register_Mod
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private String registerMod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Third_party_id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    private String thirdPartyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Id
     *
     * @return the value of user_info.Id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Id
     *
     * @param id the value for user_info.Id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Name
     *
     * @return the value of user_info.Name
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Name
     *
     * @param name the value for user_info.Name
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Gender
     *
     * @return the value of user_info.Gender
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Gender
     *
     * @param gender the value for user_info.Gender
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Age
     *
     * @return the value of user_info.Age
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Age
     *
     * @param age the value for user_info.Age
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Phone
     *
     * @return the value of user_info.Phone
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Phone
     *
     * @param phone the value for user_info.Phone
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Register_Mod
     *
     * @return the value of user_info.Register_Mod
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public String getRegisterMod() {
        return registerMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Register_Mod
     *
     * @param registerMod the value for user_info.Register_Mod
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setRegisterMod(String registerMod) {
        this.registerMod = registerMod == null ? null : registerMod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Third_party_id
     *
     * @return the value of user_info.Third_party_id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public String getThirdPartyId() {
        return thirdPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Third_party_id
     *
     * @param thirdPartyId the value for user_info.Third_party_id
     *
     * @mbg.generated Thu Dec 22 21:34:19 AEDT 2022
     */
    public void setThirdPartyId(String thirdPartyId) {
        this.thirdPartyId = thirdPartyId == null ? null : thirdPartyId.trim();
    }
}